development:
  adapter: postgresql
  encoding: unicode
  database: lamposter_dev
  pool: 5
  username: Bobarian
  password: B00b00s3x

test:
  adapter: postgresql
  encoding: unicode
  database: lamposter_test
  pool: 5
  username: Bobarian
  password: B00b00s3x
